language: ruby
rvm:
  - 2.1.2

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gnash libagg-dev automake autoconf libtool libltdl-dev libjpeg-dev libgif-dev libboost-dev libboost-thread-dev libboost-program-options-dev libfontconfig1-dev libfreetype6-dev ffmpeg libpng-dev libspeex-dev libsdl-dev libspeexdsp-dev imagemagick

script:
  - rspec spec
